files/main/routes.py
from files.models import Category

from flask import Blueprint, render_template

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/main')
@main.route('/home')
def home():
    return render_template("home.html", Category=Category)

files/posts/routes.py
import secrets
import os
from files import db
from flask import render_template, redirect, url_for, flash, request, Blueprint
from files.models import Article, User, Comment, Category
from files.posts.forms import AdminForm, CommentForm, CategoryForm
from flask_login import current_user, login_required
from datetime import datetime, timezone

posts = Blueprint('posts', __name__)

@posts.route('/articles/<article_name>', methods=['GET', 'POST']) # dynamic route
def article(article_name):
    comment_section = request.args.get("comment_section", 1, type=int)
    article = Article.query.filter_by(title = article_name).first()
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(user_id=current_user.id, article_id=Article.query.filter_by(title = article_name).first().id, user_comment= form.comment.data, date=datetime.utcnow())
        db.session.add(comment)
        db.session.commit()
        flash(f"Comment is Posted!", category='succesful')
        return redirect(url_for("posts.article", article_name=article_name))
    else:
        for error in form.errors.values():
            flash(f"{error[0]}", category='danger')

    return render_template("article.html", article_name=article_name, article=article, 
    Comments=Comment.query.filter_by(article_id=article.id).order_by(Comment.id.desc()).paginate(per_page=5, page=comment_section), 
    current_user=current_user, form=form, Category=Category, User=User)#timezone=handler.getDetails(ip_address=request.remote_addr).timezone # timezone won't work due to localhost

@posts.route('/articles')
def articles():
    page = request.args.get("page", 1, type=int)
    return render_template("articles.html", Articles=Article.query.order_by(Article.id.desc()).paginate(per_page=5, page=page), now = datetime.utcnow(), timezone=timezone, User=User, Category=Category, page=page)

@posts.route('/admin_page', methods=['GET', 'POST'])
@login_required
def admin_control():
    if current_user.user_name != "Admin":
        return redirect(url_for("main.home"))
    form = AdminForm()
    form_category = CategoryForm()
    if form.validate_on_submit():
        article = Article(title=form.title.data, article_content=form.article_content.data, abstract=form.abstract.data, user_id=current_user.id, category_id=Category.query.filter_by(category_name=form.category.data).first().id)
        db.session.add(article)
        db.session.commit()
        flash("Article is published", category='success')
        return redirect(url_for("posts.article", article_name=form.title.data))
    
    if form_category.validate_on_submit():
        category = Category(category_name=form_category.category.data)
        db.session.add(category)
        db.session.commit()
        flash("Category is added", category='success')
        return redirect(url_for("posts.category", category=form_category.category.data))
    
    if form.errors:
        for error in form.errors.values():
            flash(f"{error[0]}", category='danger')

    if form_category.errors:
        for error in form_category.errors.values():
            flash(f"{error[0]}", category='danger')

    return render_template("admin.html", form = form, form_category=form_category, Category=Category)

@posts.route('/<category>')
def category(category):
    category_ = Category.query.filter_by(category_name = category).first()
    page = request.args.get("page", 1, type=int)
    return render_template("category.html", Article=Article.query.filter_by(category_id=category_.id).order_by(Article.id.desc()).paginate(per_page=5, page=page),
     now = datetime.utcnow(), timezone=timezone, category_=category_, Category=Category)

files/user/routes.py
import secrets
import os
from files import db, bcrypt, handler
from flask import render_template, redirect, url_for, flash, request, Blueprint
from files.models import Article, User, Comment, Category
from files.user.forms import RegisterForm, LoginForm, AccountForm
from flask_login import login_user, current_user, logout_user, login_required
from datetime import datetime, timezone
from files.user.utils import save_image

users = Blueprint('users', __name__)

@users.route('/users/<user_name>', methods=['GET', 'POST'])
def account_page(user_name):
    form = AccountForm()
    if current_user.is_authenticated and current_user.user_name == user_name:
        if request.method == "GET":
            form.username.data = current_user.user_name
            form.username_new.data = current_user.user_name
        if form.validate_on_submit():
            if form.image.data:
                if current_user.image:
                    os.remove(os.path.join(os.path.dirname(__file__), url_for("static", filename="img/" + current_user.image)[1:]))
                image_file = save_image(form.image.data)
                current_user.image = image_file
                flash("Profile picture has been updated", category='success')
            if form.password_new.data:
                current_user.password= bcrypt.generate_password_hash(form.password_new.data).decode('utf-8')
                flash("Password has been updated", category='success')
            if form.username_new.data:
                current_user.user_name= form.username_new.data
                flash("User name has been updated", category='success')
            db.session.commit()
            flash("Your info has been updated", category="succesful")
            return redirect(url_for('users.account_page', user_name=current_user.user_name))
        if form.errors:
            for error in form.errors.values():
                flash(f"{error[0]}", category='danger')
    image_file = url_for("static", filename="img/" + User.query.filter_by(user_name=user_name).first().image)
    return render_template("account.html", User=User, user_name=user_name, image_file=image_file, Category=Category, form=form, current_user=current_user, Comment=Comment, datetime=datetime)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():  
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        hashed_ip = bcrypt.generate_password_hash(request.remote_addr).decode('utf-8')
        user = User(user_name=form.username.data,password=hashed_password,ip_address=hashed_ip)
        db.session.add(user)
        db.session.commit()
        login_user(user, remember=True)
        next_page = request.args.get('next')
        flash("Created Account", category='success')
        return redirect(next_page) if next_page else redirect(url_for("main.home"))  
    if form.errors:
        for error in form.errors.values():
            flash(f"{error[0]}", category='danger')

    return render_template("register.html", form = form, Category=Category)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(user_name=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=True)
            flash("Logged In", category='success')
            next_page = request.args.get('next') ## in case i decide to do something exclusive to users
            return redirect(next_page) if next_page else redirect(url_for("main.home"))  
        else:
            flash("Password or Username is not correct", category='danger')
    if form.errors:
        for error in form.errors.values():
            flash(f"{error[0]}", category='danger')
    return render_template("login.html", form = form, Category=Category)

@users.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    flash('Logged Out', category="success")
    return redirect(url_for("main.home"))

files/templates/account.html
{%extends "boiler_plate.html"%}
{%block title%} {{user_name}} {%endblock%}
{%block body%}

<div class="container">
    {%if current_user.user_name == user_name %}
    <div class="flex-wrap row">
        <div class="account flex-grow-1 col-6 mt-5 mb-5 px-5">
            <div class="d-flex justify-content-around mb-4 flex-wrap">
                <img src="{{image_file}}" alt="Profile Picture" width="128px" class="border border-warning rounded">
                <h3 class="align-self-center" >{{user_name}}</h3>
            </div>
            <hr>
            <h3>Comments</h3>
                {%for comment in User.query.filter_by(user_name=user_name).first().comments%}
                <div class="d-flex flex-row flex-wrap p-3 mb-4">                    
                      <div class="w-100 ms-3">
                            <h5>Article Title: {{comment.article.title}}</h5>
                            <hr>
                          <div class="d-flex justify-content-between align-items-center mt-2">
                              <small>{{comment.date.strftime("%y-%m-%d %H:%M")}}   </small>
                              <small>{{comment.user.user_name}}</small>
                          </div>
                          <p class="text-justify comment-text mb-0">{{comment.user_comment}}</p>
                      </div>
                  </div>
                {%endfor%}
            <h3>Articles</h3>
                
                <div class="p-3 ms-3 mb-4">
                    {%for article in User.query.filter_by(user_name=user_name).first().articles%}
                        <div class="d-flex justify-content-between">
                            <h4>{{article.title}}</h4>
                            <p>{{article.date.strftime("%y-%m-%d %H:%M")}} </p>
                        </div>    
                        <hr>
                    {%endfor%}
                </div>   
        </div>
        
        <form method="POST" class="mt-5 mb-5 flex-wrap " enctype="multipart/form-data" style="max-width: 500px;">
            {{form.hidden_tag()}}
            <div class="d-flex mb-3 justify-content-around flex-wrap">
                <div class="">
                    {{form.username.label(class="form-label")}}
                    {{form.username(class="form-control", placeholder="User Name")}}
                </div>
                <div class="">
                    {{form.username_new.label(class="form-label")}}
                    {{form.username_new(class="form-control", placeholder="New User Name")}}
                </div>
            </div>
            <div class="d-flex mb-4 justify-content-around flex-wrap">
                <div class="">
                    {{form.password.label(class="form-label")}}
                    {{form.password(class="form-control", placeholder="Password")}}
                </div>
                <div class="">
                    {{form.password_new.label(class="form-label")}}
                    {{form.password_new(class="form-control", placeholder="New Password")}}
                </div>
            </div>
            <hr>
            <div class="mb-3">
                {{form.image.label(class="form-label")}}
                {{form.image(class="form-control-file")}}
            </div>
            <div class="mb-3 scale" >
                {{form.submit(class="btn btn-primary w-100")}}
            </div>
        </form>
    </div>
    {%else%}
    <div class="d-flex justify-content-center">
        <div class="account col-6 mt-5 mb-5 px-5">
            <div class="d-flex justify-content-around mb-4">
                <img src="{{image_file}}" alt="Profile Picture" width="128px" class="border border-warning rounded">
                <h3 class="align-self-center" >{{user_name}}</h3>
            </div>
            <hr>
            <h3>Comments</h3>
                {%for comment in User.query.filter_by(user_name=user_name).first().comments%}
                <div class="d-flex flex-row p-3 mb-4">                    
                      <div class="w-100 ms-3">
                            <h5>Article Title: {{comment.article.title}}</h5>
                            <hr>
                          <div class="d-flex justify-content-between align-items-center mt-2">
                              <small>{{comment.date.strftime("%y-%m-%d %H:%M")}}   </small>
                              <small>{{comment.user.user_name}}</small>
                          </div>
                          <p class="text-justify comment-text mb-0">{{comment.user_comment}}</p>
                      </div>
                  </div>
                {%endfor%}
            <h3>Articles</h3>
                
                <div class="p-3 ms-3 mb-4">
                    {%for article in User.query.filter_by(user_name=user_name).first().articles%}
                        <div class="d-flex justify-content-between">
                            <h4>{{article.title}}</h4>
                            <p>{{article.date.strftime("%y-%m-%d %H:%M")}} </p>
                        </div>    
                        <hr>
                    {%endfor%}
                </div>   
        </div>
    </div>

    {%endif%}
</div>
{%endblock%}

files/templates/admin.html
{%extends "boiler_plate.html"%}
{%block title%} Panel {%endblock%}
{%block body%}
  <div class="container">
      <h1 class="mt-5 mb-4 text-center">Admin Panel</h1>
  <form method="POST" class="admin_form">
      {{form.hidden_tag()}}
      <div class="mb-3">
        {{form.title.label(class="form-label")}}
        {{form.title(class="form-control")}}
      </div>
      <div class="mb-3">
        {{form.category.label(class="form-label")}}
        {{form.category(class="form-control")}}
      </div>
      <div class="mb-3">
        {{form.abstract.label(class="form-label")}}
        {{form.abstract(class="form-control")}}
      </div>
      <div class="mb-3">
        {{form.article_content.label(class="form-label")}}
        {{form.article_content(class="form-control")}}
      </div>
      {{form.submit(class="btn-primary btn mb-5 scale")}}
    </form>
    <form method="POST" class="admin_form">
      {{form.hidden_tag()}}
      <div class="mb-3">
        {{form_category.category.label(class="form-label")}}
        {{form_category.category(class="form-control")}}
      </div>
      {{form.submit(class="btn-primary btn mb-5 scale")}}
    </form>
  </div>

{%endblock%}

files/templates/article.html
{%extends "boiler_plate.html"%}
{%block title%} {{article_name}} {%endblock%}
{%block body%}
<div class="container p-4">
  <h1 class="mb-5 mt-5 text-center">{{article.title}}</h1>
  <div class="row">
    <div class="col-sm-9 card p-3 word-wrap text-wrap" id="article_content">
      <div class="d-flex justify-content-between">
        <div class="float-left">{{article.date.strftime("%y-%m-%d %H:%M")}} </div>
        <div class="float-right"><a
            href="{{url_for('users.account_page', user_name=article.user.user_name)}}">{{article.user.user_name}}</a>
        </div>
      </div>
      <br>
      {{article.article_content | safe}}
    </div>
    <div class="col-sm-3">
      One of three columns
    </div>
  </div>
</div>

<div class="container mt-5 mb-5">
  <div class="row height d-flex align-items-center">
    <div class="col-md-7">
      <div class="card">
        <div class="p-3">
          <h6>Comments - {{Comments.total}}</h6>
        </div>
        {%if current_user.is_authenticated %}
        {{form.hidden_tag()}}
        <form class="mt-3 d-flex flex-row p-3 mx-0" id="comment" method="POST">
          {{ form.csrf_token() }}
          {{form.comment(class="form-control", placeholder="Enter your comment " + current_user.user_name)}}
          {{form.submit(class="btn btn-primary")}}
        </form>
        {%endif%}
        <div class="mt-2">
          {%for comment in Comments.items%}
          <hr class="dropdown-divider">
          <div class="d-flex flex-row p-3 m-{{margin}}">
            <img src="{{url_for('static', filename='img/' + comment.user.image)}}" width="50" height="50"
              class="rounded-circle mr-3">
            <div class="w-100 ms-3">
              <div class="d-flex justify-content-between align-items-center">
                <small>{{comment.date.strftime("%y-%m-%d %H:%M")}} <a
                    href="{{url_for('users.account_page', user_name=comment.user.user_name)}}">{{comment.user.user_name}}</a></small>
              </div>
              <p class="text-justify comment-text mb-0">{{comment.user_comment}}</p>
            </div>
          </div>
        </div>
          <div class="m-1">
            {%endfor%}
            {%for section in Comments.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2)%}
              {%if section%}
                {%if section == Comments.page%}
                <a href="{{url_for('posts.article', article_name=article_name, page=section)}}" class="btn btn-info">
                  {{section}}</a>
                {%else%}
                <a href="{{url_for('posts.article', article_name=article_name, page=section)}}"class="btn btn-outline-info"> {{section}}</a>
                {%endif%}
              {%else%}
              <span>...</span>
              {%endif%}
            {%endfor%}
          </div>
      </div>
    </div>
  </div>
</div>

{%endblock%}

files/templates/articles.html
{%extends "boiler_plate.html"%}
{%block title%} Articles {%endblock%}
{%block body%}
<div class="container">
  <h1 class="display-4 mt-5 mb-5 text-danger text-center">Articles
    <sub>
      <h6 class="muted">Articles - {{Articles.total}}</h6>
    </sub>
  </h1>
  {%for article in Articles.items%}
  <div class="card mb-5 mx-auto">
    <div class=" card-header">
      <span class="">{{article.date.replace(tzinfo=timezone.utc).strftime("%y-%m-%d %H:%M")}}</span>
    </div>
    <div class="card-body">
      <h5 class="card-title mt-2 mb-3">{{article.title}}</h5>
      <p class="card-text">{{article.abstract | safe}}</p>
      <address class="author blockquote-footer my-3"><a
          href="{{url_for('users.account_page', user_name=article.user.user_name)}}">{{article.user.user_name}}</a>
      </address>
      <a href="{{url_for('posts.article', article_name=article.title)}}" class="btn btn-primary"> Read More </a>
    </div>
    <div class="card-footer text-muted text-center">
      {{(now - article.date)}} ago
    </div>
  </div>
  {%endfor%}
  <div class="text-center m-3">
  {%for page in Articles.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2)%}
    {%if page%}
      {%if Articles.page == page%}
      <a href="{{url_for('posts.articles', page=page)}}" class="btn-info btn"> {{page}}</a>
      {%else%}
      <a href="{{url_for('posts.articles', page=page)}}" class="btn btn-outline-info"> {{page}}</a>
      {%endif%}
    {%else%}
    <span>...</span>
    {%endif%}
  {%endfor%}
  </div>
</div>
{%endblock%}

files/templates/boiler_plate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/tiger.ico') }}">
    
    <title>{%block title%}Boiler{%endblock%}</title>
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='bootstrap.min.css')}}">
</head>
<body class="bg-light">
    <nav class="navbar navbar-dark bg-primary navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand text-danger" href="{{url_for('main.home')}}">Æ</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse border-light" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active text-dark" aria-current="page" href="{{url_for('main.home')}}">About</a>
              </li>
              {%if current_user%}
                {%if current_user.user_name == 'Admin'%}  
                <li class="nav-item">
                  <a class="nav-link active text-warning" aria-current="page" href="{{url_for('posts.admin_control')}}">Panel</a>
                </li>
                {%endif%}
                {%if not current_user.is_authenticated%}            
                <li class="nav-item">
                  <a class="nav-link active text-dark" aria-current="page" href="{{url_for('users.register')}}">Register</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active text-dark" aria-current="page" href="{{url_for('users.login')}}">Sign in</a>
                </li>
                {%else%}
                <li class="nav-item">
                  <a class="nav-link active text-dark" aria-current="page" href="{{url_for('users.logout')}}">Logout</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active text-dark" aria-current="page" href="{{url_for('users.account_page', user_name = current_user.user_name)}}">Account</a>
                </li>
                {%endif%}
              {%endif%}

              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-dark" href="{{url_for('posts.articles')}}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Articles
                </a>
                
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                {%for category_ in Category.query.all()%}
                  <li><a class="dropdown-item" href="/{{category_.category_name}}">{{category_.category_name}}</a></li>                  
                {%endfor%}
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{{url_for('posts.articles')}}">Articles</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" id="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      {%with messages = get_flashed_messages(with_categories=true)%}
        {%if messages%}
          {%for category, message in messages %}
          {%if category == 'danger'%}
            <div class="alert alert-{{category}} alert-dismissible fade show mb-0" role="alert">
              <strong>An Error Occurred: </strong> {{message}}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {%endif%}
          {%if category == 'success'%}
            <div class="alert alert-{{category}} alert-dismissible fade show mb-0" role="alert">
              <strong>Succesfully! </strong> {{message}}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {%endif%}
          {%endfor%}
        {%endif%}
      {%endwith%}

      {%block body%}{%endblock%}

      <footer class="footer py-2 bg-primary">
        <div class="container" id="footer">
          <span><small>&copy; Copyright 2021, Ar-Ed</small></span>
        </div>
      </footer>

<script src="{{url_for('static', filename = 'bootstrap.min.js')}}" crossorigin="anonymous"></script> 

</body>
</html>

files/templates/category.html
{%extends "boiler_plate.html"%}
{%block title%} {{category}} {%endblock%}
{%block body%}
<div class="container">
    {%if category_%}
    <h1 class="display-4 mt-5 mb-5 text-danger text-center">{{category}} 
      <sub><h6 class="muted">Articles - {{Article.total}}</h6></sub> 
    </h1>
    {%for article in Article.items%}
      <div class="card mb-5 mx-auto">
          <div class=" card-header">
            <span class="">{{article.date.replace(tzinfo=timezone.utc).strftime("%y-%m-%d %H:%M")}}</span>
          </div>
          <div class="card-body">
            <h5 class="card-title mt-2 mb-3">{{article.title}}</h5>
            <p class="card-text">{{article.abstract | safe}}</p>
            <address class="author blockquote-footer my-3"><a href="{{url_for('users.account_page', user_name=article.user.user_name)}}">{{article.user.user_name}}</a></address>
            <a href="{{url_for('posts.article', article_name=article.title)}}" class="btn btn-primary"> Read More </a>
          </div>
          <div class="card-footer text-muted text-center">
            {{(now - article.date)}} ago
          </div>
      </div>
    {%endfor%}
    {%else%}
      <h1 class="display-4 mt-5 mb-5 text-danger text-center"><del>{{category}}</del></h1>
      <h3 class="mt-5 text-danger text-center">There is no such category</h3>
    {%endif%}
    
    <div class="text-center m-3">
      {%for page in Article.iter_pages(left_edge=1,right_edge=1, left_current=1, right_current=2)%}
        {%if page%}
          {%if Article.page == page%}
          <a href="{{url_for('posts.articles', page=page)}}" class="btn-info btn"> {{page}}</a>
          {%else%}
          <a href="{{url_for('posts.articles', page=page)}}" class="btn btn-outline-info"> {{page}}</a>
          {%endif%}
        {%else%}
        <span>...</span>
        {%endif%}
      {%endfor%}
      </div>
</div>
{%endblock%}

files/templates/home.html
{%extends "boiler_plate.html"%}
{%block title%} Home {%endblock%}
{%block body%}
<div class="container">
    <h1>Home</h1>
</div>
{%endblock%}

files/templates/login.html
{%extends "boiler_plate.html"%}
{%block title%} Sign in {%endblock%}
{%block body%}
<div class="container">
    <h2 class="mt-5 text-danger display-1 text-center">Æ</h2>
    <form method="POST" class="mt-5">
        {{form.hidden_tag()}}
        <div class="mb-4 my-auto">
            {{form.username.label(class="form-label")}}
            {{form.username(class="form-control", placeholder="User Name")}}
        </div>
        <div class="mb-4">
            {{form.password.label(class="form-label")}}
            {{form.password(class="form-control", placeholder="Password")}}
        </div>
        <div class="mb-4 scale" >
            {{form.submit(class="btn btn-primary w-100")}}
        </div>
    </form>
    
    <form method="get" action="{{url_for('users.register')}}" class="mb-5">
        <button class="btn btn-dark w-100 scale" value="Don't have an account?">
            Don't have an account?
        </button>
    </form>
</div>
{%endblock%}

files/templates/register.html
{%extends "boiler_plate.html"%}
{%block title%} Register {%endblock%}
{%block body%}
<div class="container">
    <h2 class="mt-5 text-danger text-center">Register</h2>
    <form method="POST" class="mt-5 mb-5">
        {{form.hidden_tag()}}
        <div class="mb-4">
            {{form.username.label(class="form-label")}}
            {{form.username(class="form-control", placeholder="User Name")}}
        </div>
        <div class="mb-4">
            {{form.password.label(class="form-label")}}
            {{form.password(class="form-control", placeholder="Password")}}
        </div>
        <div class="mb-5">
            {{form.password_check.label(class="form-label")}}
            {{form.password_check(class="form-control", placeholder="Password")}}
        </div>
        <div class="mb-5 scale" >
            {{form.submit(class="btn btn-primary w-100")}}
        </div>
    </form>
</div>
{%endblock%}